nodeLinker: pnp

packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@3.2.1"
      "#supports-color": "npm:supports-color@9.2.2"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
